### ISSUE TITLE
我想用php实现，不会py，要问一下，怎么解决同一时间戳发送消息的问题

### ISSUE THREAD

**Issue by hwm124568** [limboy/chat#1]
zadd（key,ts,content） ts一样时后一条会重写掉前一条，你是怎么解决的

**Comment by limboy** [comment]
zadd (key, ts, content) ts 一样，后一条不会覆盖前一条啊。`ts`是score，可以有多个item是相同的score。不过`content`一样的话，倒是会更新ts的值，相当于覆盖了之前的content。可以对content做一下特殊处理。

**Comment by hwm124568** [comment]
如果ts一样的话，无论内容是否一样，实际上都会丢失一条数据，现在就是没有好办法解决这个

------------------ 原始邮件 ------------------
发件人: "Limboy"notifications@github.com;
发送时间: 2013年5月31日(星期五) 晚上8:24
收件人: "lzyy/chat"chat@noreply.github.com; 
抄送: "雾失楼台/ty"272414025@qq.com; 
主题: Re: [chat] 我想用php实现，不会py，要问一下，怎么解决同一时间戳发送消息的问题 (#1)

zadd (key, ts, content) ts 一样，后一条不会覆盖前一条啊。ts是score，可以有多个item是相同的score。不过content一样的话，倒是会更新ts的值，相当于覆盖了之前的content。可以对content做一下特殊处理。

**Comment by limboy** [comment]
为什么会丢失一条数据？

**Comment by hwm124568** [comment]
恩，是我弄错了，同一个score 不同的value可以存进去，但value的排序方式好像不是按照插入顺序排序的，所以这里要特殊处理下，谢谢！

------------------ 原始邮件 ------------------
发件人: "Limboy"notifications@github.com;
发送时间: 2013年5月31日(星期五) 晚上8:31
收件人: "lzyy/chat"chat@noreply.github.com; 
抄送: "雾失楼台/ty"272414025@qq.com; 
主题: Re: [chat] 我想用php实现，不会py，要问一下，怎么解决同一时间戳发送消息的问题 (#1)

为什么会丢失一条数据？

**Comment by hwm124568** [comment]
虽然不懂PY，大致看了下大哥的PY程序，我尝试用php弄，请教大哥我以web的ajax长轮循的方式实现，现有问题如下：以时间戳为score插入记录时，例在同一个时间点插入了1000条记录，当插入100条记录时，php以当前时间戳，+inf查询了列表，将这100条记录提走了，但是剩下的900条记录是后一步插入的，
下一次轮循时会以这个score为起始，但不包含，+inf，获取数据，这个时候900条记录就丢了，或是包含当前score，但又有100条重复的，请问有好的解决方法吗

用list做，可以把当前轮循的长度记下来，下次按长度，-1请求数据，但是遇到删除后，长度变了，也会出问题，

想了半天找不到好的方法，请帮忙指点下，谢谢！
